CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730003847_InitialCreate') THEN
    CREATE TABLE "Reclamos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Tipo" text,
        "Descripcion" text,
        "Direccion" text,
        "Zona" text,
        "Latitud" double precision NOT NULL,
        "Longitud" double precision NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reclamos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730003847_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730003847_InitialCreate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730022525_ActualizacionReclamos') THEN
    ALTER TABLE "Reclamos" ADD "Apoyos" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730022525_ActualizacionReclamos') THEN
    ALTER TABLE "Reclamos" ADD "Estado" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730022525_ActualizacionReclamos') THEN
    ALTER TABLE "Reclamos" ADD "FotoUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730022525_ActualizacionReclamos') THEN
    ALTER TABLE "Reclamos" ADD "Titulo" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730022525_ActualizacionReclamos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730022525_ActualizacionReclamos', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "Nombre" text NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731193042_AddIdentity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731193042_AddIdentity', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731202102_AgregarApoyos') THEN
    CREATE TABLE "Apoyos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReclamoId" integer NOT NULL,
        "UsuarioId" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Apoyos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Apoyos_AspNetUsers_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Apoyos_Reclamos_ReclamoId" FOREIGN KEY ("ReclamoId") REFERENCES "Reclamos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731202102_AgregarApoyos') THEN
    CREATE UNIQUE INDEX "IX_Apoyos_ReclamoId_UsuarioId" ON "Apoyos" ("ReclamoId", "UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731202102_AgregarApoyos') THEN
    CREATE INDEX "IX_Apoyos_UsuarioId" ON "Apoyos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731202102_AgregarApoyos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731202102_AgregarApoyos', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731202935_RelacionesUsuariosApoyos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731202935_RelacionesUsuariosApoyos', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731203831_AgregarUsuarioAReclamos') THEN
    ALTER TABLE "Reclamos" ADD "UsuarioId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731203831_AgregarUsuarioAReclamos') THEN
    CREATE INDEX "IX_Reclamos_UsuarioId" ON "Reclamos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731203831_AgregarUsuarioAReclamos') THEN
    ALTER TABLE "Reclamos" ADD CONSTRAINT "FK_Reclamos_AspNetUsers_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731203831_AgregarUsuarioAReclamos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731203831_AgregarUsuarioAReclamos', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    DROP INDEX "IX_Apoyos_ReclamoId_UsuarioId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    ALTER TABLE "Reclamos" DROP COLUMN "Apoyos";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    ALTER TABLE "Apoyos" ADD "ApplicationUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    CREATE INDEX "IX_Apoyos_ApplicationUserId" ON "Apoyos" ("ApplicationUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    CREATE INDEX "IX_Apoyos_ReclamoId" ON "Apoyos" ("ReclamoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    ALTER TABLE "Apoyos" ADD CONSTRAINT "FK_Apoyos_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731221231_ConfigurarRelacionesApoyos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731221231_ConfigurarRelacionesApoyos', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731222131_CrearHistorialEstados') THEN
    CREATE TABLE "HistorialEstados" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReclamoId" integer NOT NULL,
        "EstadoAnterior" text NOT NULL,
        "EstadoNuevo" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "UsuarioId" text NOT NULL,
        CONSTRAINT "PK_HistorialEstados" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HistorialEstados_AspNetUsers_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_HistorialEstados_Reclamos_ReclamoId" FOREIGN KEY ("ReclamoId") REFERENCES "Reclamos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731222131_CrearHistorialEstados') THEN
    CREATE INDEX "IX_HistorialEstados_ReclamoId" ON "HistorialEstados" ("ReclamoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731222131_CrearHistorialEstados') THEN
    CREATE INDEX "IX_HistorialEstados_UsuarioId" ON "HistorialEstados" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731222131_CrearHistorialEstados') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731222131_CrearHistorialEstados', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731231426_AgregarAdministradorReclamo') THEN
    ALTER TABLE "Reclamos" ADD "AdministradorId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731231426_AgregarAdministradorReclamo') THEN
    CREATE INDEX "IX_Reclamos_AdministradorId" ON "Reclamos" ("AdministradorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731231426_AgregarAdministradorReclamo') THEN
    ALTER TABLE "Reclamos" ADD CONSTRAINT "FK_Reclamos_AspNetUsers_AdministradorId" FOREIGN KEY ("AdministradorId") REFERENCES "AspNetUsers" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731231426_AgregarAdministradorReclamo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731231426_AgregarAdministradorReclamo', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812012205_RestoreUniqueApoyo') THEN
    DELETE FROM "Apoyos" AS duplicado
    USING "Apoyos" AS original
    WHERE duplicado."ReclamoId" = original."ReclamoId"
      AND duplicado."UsuarioId" = original."UsuarioId"
      AND duplicado."Id" > original."Id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812012205_RestoreUniqueApoyo') THEN
    DROP INDEX "IX_Apoyos_ReclamoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812012205_RestoreUniqueApoyo') THEN
    CREATE UNIQUE INDEX "IX_Apoyos_ReclamoId_UsuarioId" ON "Apoyos" ("ReclamoId", "UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812012205_RestoreUniqueApoyo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812012205_RestoreUniqueApoyo', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812023657_PersistirObrasPublicas') THEN
    CREATE TABLE "ObrasAniosSincronizados" (
        "Anio" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompletadaUtc" timestamp with time zone NOT NULL,
        "Cantidad" integer NOT NULL,
        CONSTRAINT "PK_ObrasAniosSincronizados" PRIMARY KEY ("Anio")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812023657_PersistirObrasPublicas') THEN
    CREATE TABLE "ObrasPublicas" (
        "EventoId" integer GENERATED BY DEFAULT AS IDENTITY,
        "AnioFuente" integer NOT NULL,
        "MesFuente" integer,
        "Nombre" character varying(500) NOT NULL,
        "Organismo" character varying(200) NOT NULL,
        "Expediente" character varying(120) NOT NULL,
        "Licitacion" character varying(120) NOT NULL,
        "UbicacionTexto" character varying(2000) NOT NULL,
        "Estado" character varying(80) NOT NULL,
        "FuenteUrl" character varying(1000) NOT NULL,
        "Plazo" character varying(120) NOT NULL,
        "TipoGeometria" character varying(40) NOT NULL,
        "PresupuestoOficial" numeric,
        "GarantiaOferta" numeric,
        "FechaApertura" timestamp with time zone,
        "SuperficieM2" double precision,
        "FrentesTrabajo" integer,
        "DocumentosJson" text NOT NULL,
        "UbicacionesJson" text NOT NULL,
        "EventosRelacionadosJson" text NOT NULL,
        "ActualizadaUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ObrasPublicas" PRIMARY KEY ("EventoId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812023657_PersistirObrasPublicas') THEN
    CREATE TABLE "ObrasTramos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ObraEventoId" integer NOT NULL,
        "Descripcion" character varying(300) NOT NULL,
        "Calle" character varying(120) NOT NULL,
        "Desde" character varying(120) NOT NULL,
        "Hasta" character varying(120) NOT NULL,
        "LatitudInicio" double precision,
        "LongitudInicio" double precision,
        "LatitudFin" double precision,
        "LongitudFin" double precision,
        CONSTRAINT "PK_ObrasTramos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ObrasTramos_ObrasPublicas_ObraEventoId" FOREIGN KEY ("ObraEventoId") REFERENCES "ObrasPublicas" ("EventoId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812023657_PersistirObrasPublicas') THEN
    CREATE INDEX "IX_ObrasPublicas_AnioFuente" ON "ObrasPublicas" ("AnioFuente");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812023657_PersistirObrasPublicas') THEN
    CREATE UNIQUE INDEX "IX_ObrasTramos_ObraEventoId_Calle_Desde_Hasta" ON "ObrasTramos" ("ObraEventoId", "Calle", "Desde", "Hasta");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812023657_PersistirObrasPublicas') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812023657_PersistirObrasPublicas', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812024123_AmpliarUbicacionObra') THEN
    ALTER TABLE "ObrasPublicas" ALTER COLUMN "UbicacionTexto" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260812024123_AmpliarUbicacionObra') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260812024123_AmpliarUbicacionObra', '10.0.10');
    END IF;
END $EF$;
COMMIT;

